package lt.codeacademy.teamroom4.onlineshop.spring.utils.Parameters;

public enum Categories {
CPU, GPU, RAM, HDD, MAINBOARD, PSU, THERMALPASTE,FANS, DESKTOPCOMPUTER, LAPTOPCOMPUTER, ALLINONECOMPUTER,MONITORS,PHONES,TABLETS,PRINTERS,GAMECONSOLES,GAMES	
}
